pipeline:
  agent:
    any
  stages:
    - stage: Build
      steps:
        - script:
            bat: 'gradlew.bat build'
    - stage: Test
      steps:
        - script:
            bat: 'gradlew.bat test'
    - stage: Deploy
      steps:
        - script:
            echo: 'Deploying...'
  post:
    always:
      - script:
          echo: 'This will always run'
