jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}
        check-latest: false
        overwrite-settings: true
        job-status: success
