name: CI Pipeline

on:
  push:
    branches:
      - main
      - development
      - feature/*

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: |
          ./gradlew.bat assemble  # Use gradlew.bat for Windows

      - name: Run Tests with Gradle
        run: |
          ./gradlew.bat test  # Use gradlew.bat for Windows
